### ISSUE TITLE
An internal error occurred during: "Checking for unused features."

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#134]
Opened our largest feature model and had a potential endless-loop in the above mentioned job. When closing Eclipse, I got the following exception on command-line:

java.lang.NullPointerException
	at de.ovgu.featureide.core.internal.BuilderMarkerHandler.deleteConfigurationMarkers(BuilderMarkerHandler.java:173)
	at de.ovgu.featureide.core.internal.FeatureProject$2.execute(FeatureProject.java:201)
	at de.ovgu.featureide.fm.core.WaitingJob$1.run(WaitingJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

**Comment by pinnecke** [comment]
As far as I can see, this exception raised because of an illegal action during a lagging ConstraintDialog. Because issue #97 fixed this, this should not be a problem any longer.

**Comment by tthuem** [comment]
Currently, when aborting a job a user may experience an illegal state and exceptions may occur.
