### ISSUE TITLE
Resource tree is locked error

### ISSUE THREAD

**Issue by meinicke** [tthuem/FeatureIDE#185]
I get this error on my console on several pcs and for different programs:

org.eclipse.core.internal.resources.ResourceException: The resource tree is locked for modifications.
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:116)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2251)
	at org.eclipse.core.internal.resources.Resource.setDerived(Resource.java:1784)
	at de.ovgu.featureide.core.builder.ComposerExtensionClass.postCompile(ComposerExtensionClass.java:284)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer.postCompile(FeatureHouseComposer.java:1092)
	at de.ovgu.featureide.core.internal.FeatureProject.checkBuildFolder(FeatureProject.java:860)
	at de.ovgu.featureide.core.internal.FeatureProject.checkBuildFolder(FeatureProject.java:856)
	at de.ovgu.featureide.core.internal.FeatureProject.checkBuildFolder(FeatureProject.java:856)
	at de.ovgu.featureide.core.internal.FeatureProject.resourceChanged(FeatureProject.java:799)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
	at org.eclipse.core.internal.resources.Marker.delete(Marker.java:71)
	at de.ovgu.featureide.featurehouse.errorpropagation.ErrorPropagation.propagateMarkers(ErrorPropagation.java:186)
	at de.ovgu.featureide.featurehouse.errorpropagation.ErrorPropagation.propagateMarkers(ErrorPropagation.java:163)
	at de.ovgu.featureide.featurehouse.errorpropagation.ErrorPropagation$1.run(ErrorPropagation.java:96)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by tthuem** [comment]
Why should the Derived flag be set during error propagation? Makes no sense to me.

**Comment by pinnecke** [comment]
I saw this issue while trying to solve issue #87. But this happens because I used Keppler (Eclispe 4.3) and because it doesn't support JDK 8 by nativ, I installed the JDK 8 PlugIn - this caused a lot of strange things and somehow broke the PlugIn Loading ability of eclipse. However, in this setting I saw the described *resource lock*. But with a fresh environment (now Eclipse 4.4) I cannot reproduce it.

**Comment by pinnecke** [comment]
Let uns try to reproduce it together on my machine these days.

**Comment by tthuem** [comment]
Sebastian has also seen this error. We think that the build process should be avoided during/after propagating error markers.

**Comment by tthuem** [comment]
Sebastian, we already discussed this issue. Can you try to fix it?

**Comment by tthuem** [comment]
The error does also happen for the hello world example of FeatureC++:

```
org.eclipse.core.internal.resources.ResourceException: The resource tree is locked for modifications.
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:116)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2251)
	at org.eclipse.core.internal.resources.Resource.setDerived(Resource.java:1784)
	at de.ovgu.featureide.core.builder.ComposerExtensionClass.postCompile(ComposerExtensionClass.java:284)
	at de.ovgu.featureide.featurecpp.FeatureCppComposer.postCompile(FeatureCppComposer.java:219)
	at de.ovgu.featureide.core.internal.FeatureProject.checkBuildFolder(FeatureProject.java:867)
	at de.ovgu.featureide.core.internal.FeatureProject.resourceChanged(FeatureProject.java:806)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by tthuem** [comment]
Does not seem to be specific to a composer, also happend for Munge:

```
org.eclipse.core.internal.resources.ResourceException: The resource tree is locked for modifications.
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:116)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2251)
	at org.eclipse.core.internal.resources.Resource.setDerived(Resource.java:1784)
	at de.ovgu.featureide.core.builder.ComposerExtensionClass.postCompile(ComposerExtensionClass.java:284)
	at de.ovgu.featureide.munge.MungePreprocessor.postCompile(MungePreprocessor.java:361)
	at de.ovgu.featureide.core.internal.FeatureProject.checkBuildFolder(FeatureProject.java:867)
	at de.ovgu.featureide.core.internal.FeatureProject.resourceChanged(FeatureProject.java:806)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:597)
	at org.eclipse.core.internal.resources.Project.build(Project.java:114)
	at de.ovgu.featureide.core.internal.FeatureProject$3.work(FeatureProject.java:539)
	at de.ovgu.featureide.fm.core.job.AStoppableJob$InnerThread.run(AStoppableJob.java:53)
```

**Comment by tthuem** [comment]
And also happened for AHEAD. Here I noticed that error markers are not properly removed:

```
org.eclipse.core.internal.resources.ResourceException: The resource tree is locked for modifications.
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:116)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2251)
	at org.eclipse.core.internal.resources.Resource.setDerived(Resource.java:1784)
	at de.ovgu.featureide.core.builder.ComposerExtensionClass.postCompile(ComposerExtensionClass.java:284)
	at de.ovgu.featureide.ahead.AheadComposer.postCompile(AheadComposer.java:337)
	at de.ovgu.featureide.core.internal.FeatureProject.checkBuildFolder(FeatureProject.java:867)
	at de.ovgu.featureide.core.internal.FeatureProject.resourceChanged(FeatureProject.java:806)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
	at org.eclipse.core.internal.resources.Marker.delete(Marker.java:71)
	at de.ovgu.featureide.ahead.wrapper.AheadWrapper$1.run(AheadWrapper.java:155)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```
