### ISSUE TITLE
Adding DeltaJ project if DeltaJ is not installed causes NullPointerException

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#194]
Tried to import all HelloWorld examples and got the following NullPointerException:

```
java.lang.NullPointerException
	at de.ovgu.featureide.core.internal.FeatureProject.getComposer(FeatureProject.java:1067)
	at de.ovgu.featureide.core.internal.FeatureProject.loadModel(FeatureProject.java:342)
	at de.ovgu.featureide.core.internal.FeatureProject.<init>(FeatureProject.java:301)
	at de.ovgu.featureide.core.CorePlugin.addProject(CorePlugin.java:206)
	at de.ovgu.featureide.core.CorePlugin.addProjects(CorePlugin.java:620)
	at de.ovgu.featureide.core.CorePlugin$3.run(CorePlugin.java:591)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

The case that not all plug-ins are installed should be handled properly. The project should be added as a FeatureIDE project, but a warning should be added to the project root. I think we have such behavior for AspectJ.

**Comment by tthuem** [comment]
This is especially problematic, as we plan to ship the next version of FeatureIDE with Eclipse 4.4 and thus without DeltaJ.
