### ISSUE TITLE
Import of the MPL hello world example leads to a parser problem with Velvet

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#196]
```
NoViableAltException(33@[])
	at de.ovgu.featureide.fm.core.io.velvet.VelvetParser.velvetModel(VelvetParser.java:179)
	at de.ovgu.featureide.fm.core.io.velvet.VelvetFeatureModelReader.parseInputStream(VelvetFeatureModelReader.java:256)
	at de.ovgu.featureide.fm.core.io.AbstractFeatureModelReader.readFromFile(AbstractFeatureModelReader.java:87)
	at de.ovgu.featureide.fm.core.io.FeatureModelReaderIFileWrapper.readFromFile(FeatureModelReaderIFileWrapper.java:75)
	at de.ovgu.featureide.core.internal.FeatureProject.loadModel(FeatureProject.java:341)
	at de.ovgu.featureide.core.internal.FeatureProject.access$8(FeatureProject.java:337)
	at de.ovgu.featureide.core.internal.FeatureProject$4.run(FeatureProject.java:896)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by tthuem** [comment]
And also the following exceptions can be found in error log:

```
java.lang.Exception: line 1:0 no viable alternative at input 'HelloWorldMSPL2'
	at de.ovgu.featureide.fm.core.io.velvet.VelvetParser.emitErrorMessage(VelvetParser.java:133)
	at org.antlr.runtime.BaseRecognizer.displayRecognitionError(BaseRecognizer.java:194)
	at org.antlr.runtime.BaseRecognizer.reportError(BaseRecognizer.java:186)
	at de.ovgu.featureide.fm.core.io.velvet.VelvetParser.velvetModel(VelvetParser.java:230)
	at de.ovgu.featureide.fm.core.io.velvet.VelvetFeatureModelReader.parseInputStream(VelvetFeatureModelReader.java:256)
	at de.ovgu.featureide.fm.core.io.AbstractFeatureModelReader.readFromFile(AbstractFeatureModelReader.java:87)
	at de.ovgu.featureide.fm.core.io.FeatureModelReaderIFileWrapper.readFromFile(FeatureModelReaderIFileWrapper.java:75)
	at de.ovgu.featureide.core.internal.FeatureProject.loadModel(FeatureProject.java:341)
	at de.ovgu.featureide.core.internal.FeatureProject.access$8(FeatureProject.java:337)
	at de.ovgu.featureide.core.internal.FeatureProject$4.run(FeatureProject.java:896)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

```
org.eclipse.core.internal.resources.ResourceException: Marker id 2972 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.setAttribute(Marker.java:237)
	at de.ovgu.featureide.fm.core.ModelMarkerHandler.createModelMarker(ModelMarkerHandler.java:63)
	at de.ovgu.featureide.fm.core.io.velvet.VelvetFeatureModelReader.throwException(VelvetFeatureModelReader.java:1060)
	at de.ovgu.featureide.fm.core.io.velvet.VelvetFeatureModelReader.checkTree(VelvetFeatureModelReader.java:1044)
	at de.ovgu.featureide.fm.core.io.velvet.VelvetFeatureModelReader.parseInputStream(VelvetFeatureModelReader.java:262)
	at de.ovgu.featureide.fm.core.io.AbstractFeatureModelReader.readFromFile(AbstractFeatureModelReader.java:87)
	at de.ovgu.featureide.fm.core.io.FeatureModelReaderIFileWrapper.readFromFile(FeatureModelReaderIFileWrapper.java:75)
	at de.ovgu.featureide.core.internal.FeatureProject.loadModel(FeatureProject.java:341)
	at de.ovgu.featureide.core.internal.FeatureProject.access$8(FeatureProject.java:337)
	at de.ovgu.featureide.core.internal.FeatureProject$4.run(FeatureProject.java:896)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by tthuem** [comment]
Having only these two MPL example projects, I also get the following exception when opening my workspace:

```
java.lang.NullPointerException
	at java.util.Hashtable.put(Unknown Source)
	at de.ovgu.featureide.fm.core.configuration.Configuration.initRoot(Configuration.java:150)
	at de.ovgu.featureide.fm.core.configuration.Configuration.<init>(Configuration.java:121)
	at de.ovgu.featureide.fm.core.configuration.Configuration.<init>(Configuration.java:106)
	at de.ovgu.featureide.core.internal.FeatureProject$5.run(FeatureProject.java:920)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```
