### ISSUE TITLE
Feature folder decorator deactivated because of NullPointerException

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#198]
Imported all HelloWorld examples, played around for some time and got this exception (probably for one of the FOP examples):

```
Exception in Decorator. The 'Feature Folder Decorator' decorator will be disabled.
```

```
java.lang.NullPointerException
	at de.ovgu.featureide.ui.decorators.FeatureFolderDecorator.decorate(FeatureFolderDecorator.java:65)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:267)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:83)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:367)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:349)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.ensureResultCached(DecorationScheduler.java:372)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:332)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by tthuem** [comment]
Just occurred again with the current master. The main problem is that the decorators will disappear until Eclipse is restarted.
