### ISSUE TITLE
Test BUpdateFeatures1000 fails on Windows

### ISSUE THREAD

**Issue by meinicke** [tthuem/FeatureIDE#236]
When I run the test BUpdateFeatures1000 I get the following error:

2015-04-13 14:18:41,390 INFO    de.ovgu.jcorridore.RuntimeConstraint - Configuration file found: /C:/Users/jmeinicke/FeatureIDE/tests/de.ovgu.featureide.fm.core-test/bin/range.properties

java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/jmeinicke/FeatureIDE/tests/de.ovgu.featureide.fm.core-test/bin/range.properties
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at de.ovgu.jcorridore.RuntimeConstraint$Configuration.<init>(RuntimeConstraint.java:82)
	at de.ovgu.jcorridore.RuntimeConstraint.loadConfiguration(RuntimeConstraint.java:210)
	at de.ovgu.jcorridore.RuntimeConstraint.inject(RuntimeConstraint.java:171)
	at de.ovgu.featureide.fm.core.experimental.BFeatureModelAnalyzerWithRuntimeConstraints.BUpdateFeatures1000(BFeatureModelAnalyzerWithRuntimeConstraints.java:405)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by pinnecke** [comment]
Bug should be not marked as critical. This happens only on Windows systems, but does not fail on Team City Build-Server (or any non-Windows OS). I'll fix it asap.

**Comment by pinnecke** [comment]
This bug is only scoped to local Windows machines and does not fail on Team City Server. However, I pushed a fix into master. Please checkout and test, if it now runs correctly and close if this bug no longer exists.
