### ISSUE TITLE
[Antenna] - Exception while calculationg 'Statistics of productline implementation'

### ISSUE THREAD

**Issue by ckruczek** [tthuem/FeatureIDE#244]
While I was trying to view the statistics of the product-line implementation in the FeatureIDE Statistics view, FeatureIDE encountered an error:

![2015-04-29-151001_428x303_scrot](https://cloud.githubusercontent.com/assets/1372724/7391517/1949940c-ee82-11e4-95a4-2de454d15a21.png)

**Comment by ckruczek** [comment]
I investigate more and found the stacktrace:

`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at de.ovgu.featureide.ui.statistics.core.composite.lazyimplementations.DirectivesNode.initChildren(DirectivesNode.java:74)
	at de.ovgu.featureide.ui.statistics.core.composite.LazyParent$1.run(LazyParent.java:58)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)`
