### ISSUE TITLE
NullPointerException when loading a feature model

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#249]
Occurred in the following project with the most recent version during refresh:

https://github.com/TUBS-ISF/spl2015.andreas.wilschko/tree/master/Andreas-Wilschko-Task1

```
java.lang.NullPointerException
	at de.ovgu.featureide.ui.views.collaboration.CollaborationView.readColorsFromFile(CollaborationView.java:869)
	at de.ovgu.featureide.ui.views.collaboration.CollaborationView.access$8(CollaborationView.java:868)
	at de.ovgu.featureide.ui.views.collaboration.CollaborationView$4.propertyChange(CollaborationView.java:424)
	at de.ovgu.featureide.fm.core.FeatureModel.fireEvent(FeatureModel.java:569)
	at de.ovgu.featureide.fm.core.FeatureModel.handleModelDataLoaded(FeatureModel.java:540)
	at de.ovgu.featureide.fm.core.io.xml.XmlFeatureModelReader.parseInputStream(XmlFeatureModelReader.java:91)
	at de.ovgu.featureide.fm.core.io.AbstractFeatureModelReader.readFromFile(AbstractFeatureModelReader.java:87)
	at de.ovgu.featureide.fm.core.io.FeatureModelReaderIFileWrapper.readFromFile(FeatureModelReaderIFileWrapper.java:75)
	at de.ovgu.featureide.core.internal.FeatureProject.loadModel(FeatureProject.java:343)
	at de.ovgu.featureide.core.internal.FeatureProject.access$9(FeatureProject.java:339)
	at de.ovgu.featureide.core.internal.FeatureProject$5.run(FeatureProject.java:922)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by tthuem** [comment]
Just noticed a weird effect: everytime I reopen the project the number of these NullPointerException in the error log is doubled. Got 1, then 2, now 4 error pop-ups.

**Comment by pinnecke** [comment]
In remote branch **issue_249**.

**Comment by tthuem** [comment]
Seems to work now. Please go ahead and merge it.
