### ISSUE TITLE
NullPointerException when composing with Munge and wrong feature name

### ISSUE THREAD

**Issue by kruegers** [tthuem/FeatureIDE#265]
When a Munge if-statement encompasses a whole source file but contains a wrong feature name is  (that is: ```/*if[Helo]*/ $filecontent /*end[Helo]*/``` instead of ```/*if[Hello]*/ $filecontent /*end[Hello]*/```) the following error message dialog is shown: 
```
!ENTRY org.eclipse.core.jobs 4 2 2015-06-11 12:11:31.204
!MESSAGE An internal error occurred during: "preprocessor annotation checking".
!STACK 0
java.lang.NullPointerException
	at org.prop4j.Node.clone(Node.java:180)
	at org.prop4j.And.clone(And.java:78)
	at de.ovgu.featureide.core.builder.preprocessor.PPComposerExtensionClass.doThreeStepExpressionCheck(PPComposerExtensionClass.java:303)
	at de.ovgu.featureide.munge.MungePreprocessor.setMarkersContradictionalFeatures(MungePreprocessor.java:319)
	at de.ovgu.featureide.munge.MungePreprocessor.processLinesOfFile(MungePreprocessor.java:252)
	at de.ovgu.featureide.munge.MungePreprocessor.annotationChecking(MungePreprocessor.java:162)
	at de.ovgu.featureide.munge.MungePreprocessor.access$1(MungePreprocessor.java:154)
	at de.ovgu.featureide.munge.MungePreprocessor$1.run(MungePreprocessor.java:145)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```
I was able to reproduce the bug in both FeatureIDE 2.7.3 and the current dev version with the Munge HelloWorld example.

**Comment by meinicke** [comment]
worksforme
