### ISSUE TITLE
Error propagation of Antenna causes NullPointerException

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#278]
``` java
java.lang.NullPointerException
	at de.ovgu.featureide.antenna.AntennaPreprocessor$1.hasMarker(AntennaPreprocessor.java:182)
	at de.ovgu.featureide.antenna.AntennaPreprocessor$1.run(AntennaPreprocessor.java:166)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

occurred when opening or importing project https://github.com/TUBS-ISF/spl2015.christian.von.krosigk/tree/master/vonKrosigk_preprocessorAMP

**Comment by meinicke** [comment]
fixed in https://github.com/tthuem/FeatureIDE/commit/fbd3482e078e3c21933a93a7d5fadcda9fc8e76b
