### ISSUE TITLE
MPL parsing and runtime errors

### ISSUE THREAD

**Issue by andykenner** [tthuem/FeatureIDE#290]
I have used the code from master to have a look at the mpl functionality.

The given helloworld causes errros directly after loading it in the example wizard.

![image](https://cloud.githubusercontent.com/assets/8641920/9489536/0cda10e4-4be2-11e5-830d-5ef6b69e4d18.png)

![image](https://cloud.githubusercontent.com/assets/8641920/9489550/24620168-4be2-11e5-8d26-90065726c63d.png)

There where no changes in the code, if have just loaded the example.

Following exception is caused in the hosting eclipse:

NoViableAltException(33@[])
	at de.ovgu.featureide.fm.core.io.velvet.VelvetParser.velvetModel(VelvetParser.java:218)
	at de.ovgu.featureide.fm.core.io.velvet.VelvetFeatureModelReader.parseInputStream(VelvetFeatureModelReader.java:263)
	at de.ovgu.featureide.fm.core.io.AbstractFeatureModelReader.readFromString(AbstractFeatureModelReader.java:113)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.readModel(FeatureModelEditor.java:645)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.checkModel(FeatureModelEditor.java:139)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelTextEditorPage.allowPageChange(FeatureModelTextEditorPage.java:139)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.pageChange(FeatureModelEditor.java:420)
	at org.eclipse.ui.part.MultiPageEditorPart$2.widgetSelected(MultiPageEditorPart.java:292)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1077)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1062)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:774)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3028)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1749)
	at org.eclipse.swt.custom.CTabFolder$1.handleEvent(CTabFolder.java:278)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

Additionaly i get this output while debugging the code:

![image](https://cloud.githubusercontent.com/assets/8641920/9489743/95c79a9c-4be3-11e5-8b47-15f60520a3d5.png)

**Comment by RSchroeter** [comment]
fixed in commit 79ba61926ef3af39337e4c8b461dd3300cffead1
